"""initial schema with all models

Revision ID: 2579a47d4a4c
Revises: 
Create Date: 2026-03-25 07:15:08.169138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2579a47d4a4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('buying_power', sa.Float(), nullable=False),
    sa.Column('net_liquidation_value', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('open_pl', sa.Float(), nullable=False),
    sa.Column('close_pl', sa.Float(), nullable=False),
    sa.Column('pending_cash', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_captured_at'), 'account_snapshots', ['captured_at'], unique=False)
    op.create_table('bot_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_memory_category'), 'bot_memory', ['category'], unique=False)
    op.create_index(op.f('ix_bot_memory_created_at'), 'bot_memory', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_memory_symbol'), 'bot_memory', ['symbol'], unique=False)
    op.create_table('earnings_calendar',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=False),
    sa.Column('reporting_time', sa.String(length=20), nullable=False),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('eps_actual', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_calendar_earnings_date'), 'earnings_calendar', ['earnings_date'], unique=False)
    op.create_index(op.f('ix_earnings_calendar_symbol'), 'earnings_calendar', ['symbol'], unique=False)
    op.create_table('execution_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('preview_summary', sa.Text(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('fill_quantity', sa.Integer(), nullable=True),
    sa.Column('execution_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_decisions_decided_at'), 'execution_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_execution_decisions_recommendation_id'), 'execution_decisions', ['recommendation_id'], unique=False)
    op.create_table('open_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('option_symbol', sa.String(length=40), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=8), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=20), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('wheel_cycle_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_orders_broker_order_id'), 'open_orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_open_orders_symbol'), 'open_orders', ['symbol'], unique=False)
    op.create_table('option_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=False),
    sa.Column('option_symbol', sa.String(length=40), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('mid', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('implied_volatility', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('vega', sa.Float(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('bid_ask_spread_pct', sa.Float(), nullable=False),
    sa.Column('premium_per_contract', sa.Float(), nullable=False),
    sa.Column('annualized_return_pct', sa.Float(), nullable=False),
    sa.Column('collateral_required', sa.Float(), nullable=False),
    sa.Column('deterministic_score', sa.Float(), nullable=False),
    sa.Column('earnings_within_dte', sa.Boolean(), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=True),
    sa.Column('passed_all_filters', sa.Boolean(), nullable=False),
    sa.Column('filter_results_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_candidates_scan_id'), 'option_candidates', ['scan_id'], unique=False)
    op.create_index(op.f('ix_option_candidates_scanned_at'), 'option_candidates', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_option_candidates_symbol'), 'option_candidates', ['symbol'], unique=False)
    op.create_table('order_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('option_symbol', sa.String(length=40), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiration', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('estimated_premium', sa.Float(), nullable=False),
    sa.Column('collateral_required', sa.Float(), nullable=False),
    sa.Column('annualized_return_pct', sa.Float(), nullable=False),
    sa.Column('conviction_level', sa.String(length=10), nullable=False),
    sa.Column('trend_state', sa.String(length=30), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('risk_passed', sa.Boolean(), nullable=False),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_fill_price', sa.Float(), nullable=True),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('actual_premium', sa.Float(), nullable=True),
    sa.Column('broker_confirmation', sa.String(length=100), nullable=True),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('wheel_cycle_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_intents_created_at'), 'order_intents', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_intents_status'), 'order_intents', ['status'], unique=False)
    op.create_index(op.f('ix_order_intents_symbol'), 'order_intents', ['symbol'], unique=False)
    op.create_index(op.f('ix_order_intents_updated_at'), 'order_intents', ['updated_at'], unique=False)
    op.create_table('order_monitor_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=False),
    sa.Column('option_bid', sa.Float(), nullable=False),
    sa.Column('option_ask', sa.Float(), nullable=False),
    sa.Column('volume_at_strike', sa.Integer(), nullable=False),
    sa.Column('open_interest_at_strike', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=False),
    sa.Column('distance_to_fill_pct', sa.Float(), nullable=False),
    sa.Column('fill_probability', sa.String(length=16), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('reprice_suggestion', sa.Float(), nullable=True),
    sa.Column('alternative_action', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_monitor_snapshots_captured_at'), 'order_monitor_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_order_monitor_snapshots_order_id'), 'order_monitor_snapshots', ['order_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('unrealized_pl', sa.Float(), nullable=False),
    sa.Column('unrealized_pl_pct', sa.Float(), nullable=False),
    sa.Column('option_symbol', sa.String(length=40), nullable=True),
    sa.Column('option_type', sa.String(length=4), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('wheel_cycle_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_captured_at'), 'positions', ['captured_at'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_wheel_cycle_id'), 'positions', ['wheel_cycle_id'], unique=False)
    op.create_table('trade_journal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('execution_decision_id', sa.String(length=36), nullable=True),
    sa.Column('wheel_cycle_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('realized_pl', sa.Float(), nullable=True),
    sa.Column('realized_pl_pct', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('original_thesis', sa.Text(), nullable=True),
    sa.Column('post_trade_notes', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('user_action_history_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_journal_created_at'), 'trade_journal', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_journal_recommendation_id'), 'trade_journal', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_trade_journal_symbol'), 'trade_journal', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_journal_wheel_cycle_id'), 'trade_journal', ['wheel_cycle_id'], unique=False)
    op.create_table('trade_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('entry_guidance', sa.Text(), nullable=False),
    sa.Column('exit_ladder_json', sa.Text(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=False),
    sa.Column('risks_json', sa.Text(), nullable=True),
    sa.Column('holding_period', sa.String(length=50), nullable=False),
    sa.Column('assignment_comfort', sa.String(length=10), nullable=True),
    sa.Column('assignment_comfort_reasoning', sa.Text(), nullable=True),
    sa.Column('would_hold_if_assigned', sa.Text(), nullable=True),
    sa.Column('earnings_risk_assessment', sa.Text(), nullable=True),
    sa.Column('recommended_strike', sa.Float(), nullable=True),
    sa.Column('recommended_premium', sa.Float(), nullable=True),
    sa.Column('recommended_contracts', sa.Integer(), nullable=True),
    sa.Column('annualized_return_pct', sa.Float(), nullable=True),
    sa.Column('allocation_mode', sa.String(length=20), nullable=False),
    sa.Column('pct_of_available_cash', sa.Float(), nullable=True),
    sa.Column('llm_model_used', sa.String(length=50), nullable=False),
    sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_completion_tokens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_recommendations_candidate_id'), 'trade_recommendations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_created_at'), 'trade_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_scan_id'), 'trade_recommendations', ['scan_id'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_symbol'), 'trade_recommendations', ['symbol'], unique=False)
    op.create_table('watchlist_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('market_cap_billions', sa.Float(), nullable=False),
    sa.Column('avg_daily_volume', sa.Float(), nullable=False),
    sa.Column('assignment_comfort', sa.String(length=10), nullable=False),
    sa.Column('assignment_notes', sa.Text(), nullable=True),
    sa.Column('next_earnings_date', sa.Date(), nullable=True),
    sa.Column('earnings_confirmed', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_symbols_symbol'), 'watchlist_symbols', ['symbol'], unique=True)
    op.create_table('wheel_cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('csp_strike', sa.Float(), nullable=True),
    sa.Column('csp_premium_received', sa.Float(), nullable=False),
    sa.Column('csp_contracts', sa.Integer(), nullable=False),
    sa.Column('csp_order_id', sa.String(length=64), nullable=True),
    sa.Column('csp_expiration', sa.String(length=10), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_shares', sa.Integer(), nullable=False),
    sa.Column('assignment_cost_basis', sa.Float(), nullable=False),
    sa.Column('cc_rounds', sa.Integer(), nullable=False),
    sa.Column('cc_total_premium_received', sa.Float(), nullable=False),
    sa.Column('cc_current_strike', sa.Float(), nullable=True),
    sa.Column('cc_current_order_id', sa.String(length=64), nullable=True),
    sa.Column('shares_sold_at', sa.Float(), nullable=True),
    sa.Column('shares_sold_method', sa.String(length=20), nullable=True),
    sa.Column('total_premium_collected', sa.Float(), nullable=False),
    sa.Column('total_realized_pl', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wheel_cycles_started_at'), 'wheel_cycles', ['started_at'], unique=False)
    op.create_index(op.f('ix_wheel_cycles_symbol'), 'wheel_cycles', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wheel_cycles_symbol'), table_name='wheel_cycles')
    op.drop_index(op.f('ix_wheel_cycles_started_at'), table_name='wheel_cycles')
    op.drop_table('wheel_cycles')
    op.drop_index(op.f('ix_watchlist_symbols_symbol'), table_name='watchlist_symbols')
    op.drop_table('watchlist_symbols')
    op.drop_index(op.f('ix_trade_recommendations_symbol'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_scan_id'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_created_at'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_candidate_id'), table_name='trade_recommendations')
    op.drop_table('trade_recommendations')
    op.drop_index(op.f('ix_trade_journal_wheel_cycle_id'), table_name='trade_journal')
    op.drop_index(op.f('ix_trade_journal_symbol'), table_name='trade_journal')
    op.drop_index(op.f('ix_trade_journal_recommendation_id'), table_name='trade_journal')
    op.drop_index(op.f('ix_trade_journal_created_at'), table_name='trade_journal')
    op.drop_table('trade_journal')
    op.drop_index(op.f('ix_positions_wheel_cycle_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_captured_at'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_order_monitor_snapshots_order_id'), table_name='order_monitor_snapshots')
    op.drop_index(op.f('ix_order_monitor_snapshots_captured_at'), table_name='order_monitor_snapshots')
    op.drop_table('order_monitor_snapshots')
    op.drop_index(op.f('ix_order_intents_updated_at'), table_name='order_intents')
    op.drop_index(op.f('ix_order_intents_symbol'), table_name='order_intents')
    op.drop_index(op.f('ix_order_intents_status'), table_name='order_intents')
    op.drop_index(op.f('ix_order_intents_created_at'), table_name='order_intents')
    op.drop_table('order_intents')
    op.drop_index(op.f('ix_option_candidates_symbol'), table_name='option_candidates')
    op.drop_index(op.f('ix_option_candidates_scanned_at'), table_name='option_candidates')
    op.drop_index(op.f('ix_option_candidates_scan_id'), table_name='option_candidates')
    op.drop_table('option_candidates')
    op.drop_index(op.f('ix_open_orders_symbol'), table_name='open_orders')
    op.drop_index(op.f('ix_open_orders_broker_order_id'), table_name='open_orders')
    op.drop_table('open_orders')
    op.drop_index(op.f('ix_execution_decisions_recommendation_id'), table_name='execution_decisions')
    op.drop_index(op.f('ix_execution_decisions_decided_at'), table_name='execution_decisions')
    op.drop_table('execution_decisions')
    op.drop_index(op.f('ix_earnings_calendar_symbol'), table_name='earnings_calendar')
    op.drop_index(op.f('ix_earnings_calendar_earnings_date'), table_name='earnings_calendar')
    op.drop_table('earnings_calendar')
    op.drop_index(op.f('ix_bot_memory_symbol'), table_name='bot_memory')
    op.drop_index(op.f('ix_bot_memory_created_at'), table_name='bot_memory')
    op.drop_index(op.f('ix_bot_memory_category'), table_name='bot_memory')
    op.drop_table('bot_memory')
    op.drop_index(op.f('ix_account_snapshots_captured_at'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
